apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-avvist-til-oppgave
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  env:
    - name: RUST_BACKTRACE
      value: "1"
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  startup:
    failureThreshold: 10
    initialDelay: 2
    path: /internal/hasStarted
    periodSeconds: 10
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    tracing:
      enabled: true
  resources:
    limits:
      memory: 8Mi
    requests:
      memory: 8Mi
      cpu: 1m
