### POST /api/v1/kartlegging
POST {{baseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "method": "POST",
    "url": "http://paw-arbeidssoekerregisteret-api-kartlegging/api/v1/kartlegging",
    "body": {
        "identitetsnummer": "{{identitetsnummer}}",
        "paging": {
            "page": 1,
            "page_size": 10,
            "sort_order": "DESC"
        }
    }
}
