### POST /api/v1/kartlegging for IDENTITETSNUMMER
POST {{baseUrl}}/api/v1/kartlegging
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "IDENTITETSNUMMER",
    "identitetsnummer": "{{identitetsnummer}}",
    "paging": {
        "page": 1,
        "pageSize": 100,
        "sortOrder": "DESC"
    }
}

### POST /api/v1/kartlegging for TILKNYTTET_KONTOR
POST {{baseUrl}}/api/v1/kartlegging
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "TILKNYTTET_KONTOR",
    "kontorId": "1234",
    "paging": {
        "page": 1,
        "pageSize": 100,
        "sortOrder": "DESC"
    }
}

### GET /api/v1/statistics
GET {{baseUrl}}/api/v1/statistics
Accept: application/json
