use base64::{
    Engine,
    engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD},
};
use paw_kafka_signing::{
    RecordSigner, RecordVerifier, SIGNATURE_HEADER, SIGNING_KEY_ID_HEADER, SignatureError,
    ValidSignature, signature_payload, strip_signing_headers,
};
use rdkafka::Message;
use rdkafka::message::{Header, Headers, OwnedHeaders, OwnedMessage, Timestamp};
use rdkafka::producer::FutureRecord;

// Deliberately non-production keypair, generated solely for JVM/Rust interoperability tests.
const PRIVATE_KEY: &str = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgTcHjbk5UsMgesz27gQae18+ywlN7oD/8r8M0VT4eXD6hRANCAARXUHblPuIyGzgOyofTZyaysNxqJRbqX+T/AaN3YZ4yunMFK5FEv9TIUqLaErcLHlKEd3nYmBlTEqWWqWkImxNj";
const PUBLIC_KEY: &str = "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEV1B25T7iMhs4DsqH02cmsrDcaiUW6l/k/wGjd2GeMrpzBSuRRL/UyFKi2hK3Cx5ShHd52JgZUxKllqlpCJsTYw==";
const TRACEPARENT: &str = "00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01";
const TIMESTAMP: i64 = 1_700_000_000_000;
// Generated by java.security.Signature("SHA256withECDSA") over Kotlin's ByteBuffer layout.
const JVM_SIGNATURE: &str = "MEQCIBx-n27W1JzwdC2HHI1CFeRwXxDNyHr1WCgOU3_PoAh3AiAT7DtNFPhSLoB0iM9HOW2YE1NofVWaGT_7_BCFTxGmKA";

fn signer() -> RecordSigner {
    RecordSigner::from_pkcs8_base64("test-ecdsa-v1", PRIVATE_KEY).unwrap()
}
fn verifier() -> RecordVerifier {
    let mut verifier = RecordVerifier::new();
    verifier.add_key("test-ecdsa-v1", PUBLIC_KEY).unwrap();
    verifier
}

fn message(headers: Option<OwnedHeaders>) -> OwnedMessage {
    OwnedMessage::new(
        Some(b"value".to_vec()),
        Some(b"key".to_vec()),
        "topic".into(),
        Timestamp::CreateTime(TIMESTAMP),
        2,
        42,
        headers,
    )
}

#[test]
fn kotlin_payload_layout_and_mutations() {
    let bytes = signature_payload(b"key", TRACEPARENT.as_bytes(), TIMESTAMP, b"value").unwrap();
    assert_eq!(&bytes[..7], b"\0\0\0\x03key");
    assert_eq!(&bytes[7..11], &[0, 0, 0, TRACEPARENT.len() as u8]);
    let timestamp_at = 11 + TRACEPARENT.len();
    assert_eq!(
        &bytes[timestamp_at..timestamp_at + 8],
        &TIMESTAMP.to_be_bytes()
    );
    assert_eq!(&bytes[timestamp_at + 8..timestamp_at + 12], &[0, 0, 0, 5]);
    assert_eq!(&bytes[timestamp_at + 12..], b"value");
}

#[test]
fn java_signed_vector_is_valid_in_rust() {
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: "traceparent",
            value: Some(TRACEPARENT),
        })
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some(JVM_SIGNATURE),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some("test-ecdsa-v1"),
        });
    assert_eq!(
        verifier().validate(&message(Some(headers))),
        Ok(ValidSignature {
            key_id: "test-ecdsa-v1".into()
        })
    );
}

// This signature was produced by the Rust signer and verified by Java's
// SHA256withECDSA using the public key above and the same signed bytes.
const RUST_SIGNATURE: &str = "MEUCIQDzxaNPDMm1uutfOMxIkpNQpvCMdK0aJgh2TmvS9z8CBgIgQ3rbl1_x5KmTeNgaC5mK0XPckRDJrXFJQMlQFozGwrc";

#[test]
fn rust_signature_for_jvm_verification() {
    let signature = signer()
        .sign(b"key", TRACEPARENT.as_bytes(), TIMESTAMP, b"value")
        .unwrap();
    assert_eq!(URL_SAFE_NO_PAD.encode(signature), RUST_SIGNATURE);
}

#[test]
fn sign_record_replaces_old_headers_and_validates_without_changing_message() {
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some("old"),
        })
        .insert(Header {
            key: "traceparent",
            value: Some("obsolete"),
        })
        .insert(Header {
            key: "traceparent",
            value: Some(TRACEPARENT),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some("old"),
        });
    let record = FutureRecord::to("topic")
        .key("key")
        .payload("value")
        .headers(headers);
    let (signed, status) = signer().sign_record(record);
    status.unwrap();
    let timestamp = signed.timestamp.unwrap();
    let headers = signed.headers.unwrap();
    assert_eq!(
        headers.iter().filter(|h| h.key == SIGNATURE_HEADER).count(),
        1
    );
    assert_eq!(headers.iter().filter(|h| h.key == "traceparent").count(), 2);
    let record = OwnedMessage::new(
        Some(b"value".to_vec()),
        Some(b"key".to_vec()),
        "topic".into(),
        Timestamp::CreateTime(timestamp),
        2,
        42,
        Some(headers),
    );
    assert_eq!(
        verifier().validate(&record),
        Ok(ValidSignature {
            key_id: "test-ecdsa-v1".into()
        })
    );
    assert_eq!(record.payload(), Some(b"value".as_slice()));
    assert_eq!(
        verifier().validate(&record.clone().set_payload(Some(b"tampered".to_vec()))),
        Err(SignatureError::InvalidSignature {
            key_id: "test-ecdsa-v1".into()
        })
    );
    assert_eq!(
        verifier().validate(&record.clone().set_key(Some(b"tampered".to_vec()))),
        Err(SignatureError::InvalidSignature {
            key_id: "test-ecdsa-v1".into()
        })
    );
    assert_eq!(
        verifier().validate(&record.set_timestamp(Timestamp::CreateTime(timestamp + 1))),
        Err(SignatureError::InvalidSignature {
            key_id: "test-ecdsa-v1".into()
        })
    );
}

#[test]
fn missing_or_bad_signatures_are_only_results_not_drops() {
    let unsigned = message(None);
    assert_eq!(
        verifier().validate(&unsigned),
        Err(SignatureError::MissingSignature)
    );
    let only_key_id = OwnedHeaders::new().insert(Header {
        key: SIGNING_KEY_ID_HEADER,
        value: Some("test-ecdsa-v1"),
    });
    assert_eq!(
        verifier().validate(&message(Some(only_key_id))),
        Err(SignatureError::MissingSignature)
    );
    let only_signature = OwnedHeaders::new().insert(Header {
        key: SIGNATURE_HEADER,
        value: Some(JVM_SIGNATURE),
    });
    assert_eq!(
        verifier().validate(&message(Some(only_signature))),
        Err(SignatureError::TechnicalError {
            reason: "missing key ID"
        })
    );
    let oversized_key_id = "x".repeat(129);
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some(JVM_SIGNATURE),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some(oversized_key_id.as_bytes()),
        });
    assert_eq!(
        verifier().validate(&message(Some(headers))),
        Err(SignatureError::TechnicalError {
            reason: "invalid key ID"
        })
    );
    let signed = signer().sign(b"key", b"", TIMESTAMP, b"value").unwrap();
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some(URL_SAFE_NO_PAD.encode(signed).as_bytes()),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some("unknown"),
        });
    assert_eq!(
        verifier().validate(&message(Some(headers))),
        Err(SignatureError::UnknownKey {
            key_id: "unknown".into()
        })
    );
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some("bad!!"),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some("test-ecdsa-v1"),
        });
    assert_eq!(
        verifier().validate(&message(Some(headers))),
        Err(SignatureError::TechnicalError {
            reason: "invalid signature base64"
        })
    );
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some(JVM_SIGNATURE),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some(&[0xff]),
        });
    assert_eq!(
        verifier().validate(&message(Some(headers))),
        Err(SignatureError::TechnicalError {
            reason: "invalid key ID encoding"
        })
    );
}

#[test]
fn absent_bytes_and_pem_wrapped_private_key() {
    let pem = format!("-----BEGIN PRIVATE KEY-----\n{PRIVATE_KEY}\n-----END PRIVATE KEY-----");
    let signer = RecordSigner::from_pkcs8_base64("test-ecdsa-v1", &pem).unwrap();
    let signature = signer.sign(b"", b"", TIMESTAMP, b"").unwrap();
    let headers = OwnedHeaders::new()
        .insert(Header {
            key: SIGNATURE_HEADER,
            value: Some(URL_SAFE_NO_PAD.encode(signature).as_bytes()),
        })
        .insert(Header {
            key: SIGNING_KEY_ID_HEADER,
            value: Some("test-ecdsa-v1"),
        });
    let msg = OwnedMessage::new(
        None,
        None,
        "topic".into(),
        Timestamp::CreateTime(TIMESTAMP),
        0,
        0,
        Some(headers),
    );
    assert_eq!(
        verifier().validate(&msg),
        Ok(ValidSignature {
            key_id: "test-ecdsa-v1".into()
        })
    );
    let empty = strip_signing_headers(msg.headers());
    assert_eq!(empty.count(), 0);
    assert_eq!(STANDARD.decode(PRIVATE_KEY).unwrap().len(), 138);
}
