host = "${NAIS_DATABASE_RUST_NAIS_API_TEST_RUST_TEST_APP_HOST}"
port = "${NAIS_DATABASE_RUST_NAIS_API_TEST_RUST_TEST_APP_PORT}"
username = "${NAIS_DATABASE_RUST_NAIS_API_TEST_RUST_TEST_APP_USERNAME}"
password = "${NAIS_DATABASE_RUST_NAIS_API_TEST_RUST_TEST_APP_PASSWORD}"
database = "${NAIS_DATABASE_RUST_NAIS_API_TEST_RUST_TEST_APP_DATABASE}"
statement_log_level = "DEBUG"
