apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-kafka-topic-backup
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  env:
    - name: PGSSLMODE
      value: "VerifyFull"
    - name: PGSSLROOTCERT
      value: "$(NAIS_DATABASE_PAW_KAFKA_TOPIC_BACKUP_TOPICBACKUPHDD_SSLROOTCERT)"
    - name: PGSSLCERT
      value: "$(NAIS_DATABASE_PAW_KAFKA_TOPIC_BACKUP_TOPICBACKUPHDD_SSLCERT)"
    - name: PGSSLKEY
      value: "$(NAIS_DATABASE_PAW_KAFKA_TOPIC_BACKUP_TOPICBACKUPHDD_SSLKEY)"
    - name: PAA_VEGNE_AV_TOPIC
      value: "paw.arbeidssoker-bekreftelse-paavegneav-v1"
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  startup:
    failureThreshold: 10
    initialDelay: 2
    path: /internal/hasStarted
    periodSeconds: 10
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: {{ kafka }}
  resources:
    limits:
      memory: 16Mi
    requests:
      memory: 16Mi
      cpu: 10m
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: topicbackuphdd
        diskType: HDD
        highAvailability: false
        pointInTimeRecovery: false
        diskAutoresize: true
        insights:
          enabled: false

