[package]
name = "veileder-oppgave"
version = "0.1.0"
edition.workspace = true

[features]
nais = []

[lib]
name = "veileder_oppgave"
path = "src/lib.rs"

[dependencies]
types = { path = "../../domain/types" }
errors = { path = "../../domain/errors" }
interne_hendelser = { path = "../../domain/interne_hendelser" }
paw_rust_base = { path = "../../lib/paw_rust_base" }
paw_kafka = { path = "../../lib/paw_kafka" }
texas_client = { path = "../../lib/texas_client" }
paw_observability = { path = "../../lib/paw_observability" }
paw_sqlx = { path = "../../lib/paw_sqlx" }
uuid = { workspace = true, features = ["serde"] }
tokio = { workspace = true }
rdkafka = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-env-field = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
async-trait = { workspace = true }
rand = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }

[dev-dependencies]
mockito = { workspace = true }
paw_test = { path = "../../lib/paw_test" }
postgres_testcontainer = { path = "../../test/postgres_testcontainer" }
