apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-utgang-pdl
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  env:
    - name: KAFKA_KEYS_SCOPE
      value: api://dev-gcp.paw.paw-kafka-key-generator/.default
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: HENDELSELOGG_TOPIC
      value: "paw.arbeidssoker-hendelseslogg-v1"
    - name: PERIODE_TOPIC
      value: "paw.arbeidssoker-periode-v1"
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ kafka }}
    streams: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 32Mi
    requests:
      cpu: 25m
      memory: 32Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  startup:
    failureThreshold: 10
    initialDelay: 2
    path: /internal/hasStarted
    periodSeconds: 10
    timeout: 5
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-f1-micro
        databases:
          - name: utgangbeta1
        highAvailability: false
        pointInTimeRecovery: false
        diskAutoresize: true
        insights:
          enabled: false
