### POST /api/v1/oversikt for IDENTITETSNUMMER
POST {{baseUrl}}/api/v1/oversikt
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "IDENTITETSNUMMER",
    "identitetsnummer": "{{identitetsnummer}}",
    "paging": {
        "page": 1,
        "pageSize": 100,
        "sortOrder": "DESC"
    }
}

### POST /api/v1/oversikt for TILKNYTTET_KONTOR
POST {{baseUrl}}/api/v1/oversikt
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "type": "TILKNYTTET_KONTOR",
    "kontorId": "4154",
    "ledigSiden": "2026-04-01",
    "paging": {
        "page": 1,
        "pageSize": 100,
        "sortOrder": "DESC"
    }
}