openapi: 3.1.0
info:
  title: PAW Arbeidssøkerregisteret Kartlegging API
  description: >-
    API for å hente kartlegging av arbeidssøkere. Kalles av saksbehandlere via Azure AD.
  license:
    name: 'Apache 2.0'
    identifier: 'Apache-2.0'
  version: 1.0.0

tags:
  - name: kartlegging
    description: Hente kartlegging av arbeidssøkere

paths:
  /api/v1/kartlegging:
    post:
      tags:
        - kartlegging
      operationId: finn_kartlegging
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
        required: true
      responses:
        '200':
          description: Oversikt over arbeidssøkere for gitt query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KartleggingResponse'
        '500':
          description: Intern feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  # SECURITY
  securitySchemes:
    BearerAuth:
      scheme: bearer
      type: http

  # REQUESTS & RESPONSES
  schemas:
    # REQUESTS
    QueryRequest:
      oneOf:
        - $ref: '#/components/schemas/IdentitetsnummerQueryRequest'
        - $ref: '#/components/schemas/TilknyttetKontorQueryRequest'
    IdentitetsnummerQueryRequest:
      type: object
      required:
        - type
        - identitetsnummer
        - paging
      properties:
        type:
          type: string
          enum:
            - IDENTITETSNUMMER
        identitetsnummer:
          type: string
        paging:
          $ref: '#/components/schemas/PagingRequest'
      example:
        type: 'IDENTITETSNUMMER'
        identitetsnummer: "01017012345"
        paging:
            page: 1
            pageSize: 1000
            sortOrder: "DESC"
    TilknyttetKontorQueryRequest:
      type: object
      required:
        - type
        - kontorId
        - paging
      properties:
        type:
          type: string
          enum:
            - TILKNYTTET_KONTOR
        kontorId:
          type: string
        kontorType:
          oneOf:
            - type: 'null'
            - $ref: '#/components/schemas/KontorType'
        ledigSiden:
          type:
            - string
            - 'null'
          format: date
        paging:
          $ref: '#/components/schemas/PagingRequest'
      example:
        type: 'TILKNYTTET_KONTOR'
        kontorId: 1337
        ledigSiden: "2021-01-01"
        paging:
          page: 1
          pageSize: 1000
          sortOrder: "DESC"
    PagingRequest:
      type: object
      required:
        - page
        - pageSize
        - sortOrder
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sortOrder:
          $ref: '#/components/schemas/SortOrder'
      example:
        page: 1
        pageSize: 1000
        sortOrder: "DESC"

    # RESPONSES
    KartleggingResponse:
      type: object
      required:
        - arbeidssoekere
        - paging
      properties:
        arbeidssoekere:
          type: array
          items:
            $ref: '#/components/schemas/Arbeidssoeker'
        paging:
          $ref: '#/components/schemas/PagingResponse'
    PagingResponse:
      type: object
      required:
        - page
        - pageSize
        - hitSize
        - totalCount
        - sortOrder
      properties:
        page:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        sortOrder:
          $ref: '#/components/schemas/SortOrder'
        hitSize:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int64
      example:
        page: 1
        pageSize: 1000
        sortOrder: "DESC"
        hitSize: 42
        totalCount: 10000
    Arbeidssoeker:
      type: object
      required:
        - arbeidssoekerId
        - identitetsnummer
        - fornavn
        - etternavn
        - ledighetsperioder
        - kontortilknytninger
      properties:
        arbeidssoekerId:
          type: integer
          format: int64
        identitetsnummer:
          type: string
        fornavn:
          type: string
        mellomnavn:
          type:
            - string
            - 'null'
        etternavn:
          type: string
        ledighetsperioder:
          type: array
          items:
            $ref: '#/components/schemas/Ledighetsperiode'
        kontortilknytninger:
          type: array
          items:
            $ref: '#/components/schemas/Kontortilknytning'
      example:
        arbeidssoekerId: 1337
        identitetsnummer: "01017012345"
        fornavn: "Kari"
        etternavn: "Nordmann"
        ledighetsperioder: []
        kontortilknytninger: [
          {
            kontorId: "1337",
            kontorNavn: "NAV Bouvetøya",
            kontorType: "ARBEIDSOPPFOLGING"
          }
        ]
    Ledighetsperiode:
      type: object
      required:
        - periode
      properties:
        ledigSiden:
          type:
            - string
            - 'null'
          format: date-time
        periode:
          $ref: '#/components/schemas/Periode'
        opplysninger:
          $ref: '#/components/schemas/Opplysninger'
        profilering:
          $ref: '#/components/schemas/Profilering'
        egenvurdering:
          $ref: '#/components/schemas/Egenvurdering'
        bekreftelse:
          $ref: '#/components/schemas/Bekreftelse'
        bekreftelsePaaVegneAv:
          type: array
          items:
            $ref: '#/components/schemas/Bekreftelsesloesning'
    Periode:
      type: object
      required:
        - id
        - startet
      properties:
        id:
          type: string
          format: uuid
        startet:
          type: string
          format: date-time
        avsluttet:
          type:
            - string
            - 'null'
          format: date-time
    Opplysninger:
      type: object
      required:
        - id
        - tidspunkt
      properties:
        id:
          type: string
          format: uuid
        tidspunkt:
          type: string
          format: date-time
    Profilering:
      type: object
      required:
        - id
        - profilertTil
        - tidspunkt
      properties:
        id:
          type: string
          format: uuid
        profilertTil:
          $ref: '#/components/schemas/ProfilertTil'
        tidspunkt:
          type: string
          format: date-time
    Egenvurdering:
      type: object
      required:
        - id
        - egenvurdertTil
        - tidspunkt
      properties:
        egenvurdertTil:
          $ref: '#/components/schemas/ProfilertTil'
        id:
          type: string
          format: uuid
        tidspunkt:
          type: string
          format: date-time
    Bekreftelse:
      type: object
      required:
        - id
        - gjelderFra
        - gjelderTil
        - harJobbet
        - vilFortsette
        - bekreftelsesloesning
      properties:
        bekreftelsesloesning:
          $ref: '#/components/schemas/Bekreftelsesloesning'
        gjelderFra:
          type: string
          format: date-time
        gjelderTil:
          type: string
          format: date-time
        harJobbet:
          type: boolean
        id:
          type: string
          format: uuid
        vilFortsette:
          type: boolean
    Kontortilknytning:
      type: object
      required:
        - kontorId
        - kontorNavn
        - kontorType
      properties:
        kontorId:
          type: string
        kontorNavn:
          type: string
        kontorType:
          $ref: '#/components/schemas/KontorType'
      example:
        kontorId: "1337"
        kontorNavn: "NAV Bouvetøya"
        kontorType: "ARBEIDSOPPFOLGING"

    # ENUMS
    ProfilertTil:
      type: string
      enum:
        - UDEFINERT
        - ANTATT_GODE_MULIGHETER
        - ANTATT_BEHOV_FOR_VEILEDNING
        - OPPGITT_HINDRINGER
        - UKJENT_VERDI
    Bekreftelsesloesning:
      type: string
      enum:
        - UKJENT_VERDI
        - ARBEIDSSOEKERREGISTERET
        - DAGPENGER
        - FRISKMELDT_TIL_ARBEIDSFORMIDLING
    KontorType:
      type: string
      enum:
        - ARENA
        - ARBEIDSOPPFOLGING
        - GEOGRAFISK_TILKNYTNING
        - UKJENT_VERDI

    # COMMON
    SortOrder:
      type: string
      enum:
        - ASC
        - DESC
    ProblemDetails:
      type: object
      required:
        - id
        - type
        - title
        - status
        - instance
        - timestamp
      properties:
        detail:
          type:
            - string
            - 'null'
        id:
          type: string
          format: uuid
        instance:
          type: string
        status:
          type: integer
          format: int32
          minimum: 0
        timestamp:
          type: string
          format: date-time
        title:
          type: string
        type:
          type: string
      example:
        id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
        type: "urn:paw:default:ukjent-feil"
        status: 500
        title: "Internal Server Error"
        detail: "Ukjent feil"
        instance: "/api/v1/kartlegging"
        timestamp: "2021-01-01T12:00:00.000Z"
