topic_hendelseslogg = "paw.arbeidssoker-hendelseslogg-v1"
topic_hendelseslogg_version = 1
topic_oppgavehendelse = "oppgavehandtering.oppgavehendelse-v1"
topic_oppgavehendelse_version = 1
opprett_oppgaver_task_interval_minutes = 1
opprett_oppgaver_task_batch_size = 50
opprett_oppgaver_fra_tidspunkt = "${OPPRETT_OPPGAVER_FRA_TIDSPUNKT}"
