topics = [
    "paw.arbeidssoker-hendelseslogg-v1"
]
opprett_oppgaver_task_interval_minutes = 1
opprett_oppgaver_task_batch_size = 10
opprett_oppgaver_fra_tidspunkt = "${OPPRETT_OPPGAVER_FRA_TIDSPUNKT}"
