host = "${NAIS_DATABASE_ARBEIDSSOEKERREGISTERET_INTERNKONTROLL_INTERNKONTROLL_HOST}"
port = "${NAIS_DATABASE_ARBEIDSSOEKERREGISTERET_INTERNKONTROLL_INTERNKONTROLL_PORT}"
username = "${NAIS_DATABASE_ARBEIDSSOEKERREGISTERET_INTERNKONTROLL_INTERNKONTROLL_USERNAME}"
password = "${NAIS_DATABASE_ARBEIDSSOEKERREGISTERET_INTERNKONTROLL_INTERNKONTROLL_PASSWORD}"
database = "${NAIS_DATABASE_ARBEIDSSOEKERREGISTERET_INTERNKONTROLL_INTERNKONTROLL_DATABASE}"
