[package]
name = "regler_arbeidssoeker"
version = "0.1.0"
edition.workspace = true

[dependencies]
interne_hendelser = { path = "../interne_hendelser" }
types = { path = "../types" }
pdl_graphql = { path = "../pdl_graphql" }
paw_rust_base = { path = "../../lib/paw_rust_base" }
thiserror = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde-env-field = { workspace = true }
strum = { workspace = true }
