use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Opplysning {
    ForhaandsgodkjentAvAnsatt,
    SammeSomInnloggetBruker,
    IkkeSammeSomInnloggerBruker,
    AnsattIkkeTilgang,
    AnsattTilgang,
    IkkeAnsatt,
    SystemIkkeTilgang,
    SystemTilgang,
    IkkeSystem,
    ErOver18Aar,
    ErUnder18Aar,
    UkjentFoedselsdato,
    UkjentFoedselsaar,
    TokenxPidIkkeFunnet,
    OpphoertIdentitet,
    IkkeBosatt,
    Doed,
    Savnet,
    HarNorskAdresse,
    HarUtenlandskAdresse,
    HarRegistrertAdresseIEuEoes,
    IngenAdresseFunnet,
    BosattEtterFregLoven,
    Dnummer,
    UkjentForenkletFregStatus,
    HarGyldigOppholdstillatelse,
    OppholdstilatellseUtgaatt,
    BarnFoedtINorgeUtenOppholdstillatelse,
    IngenInformasjonOmOppholdstillatelse,
    UkjentStatusForOppholdstillatelse,
    PersonIkkeFunnet,
    SisteFlyttingVarUtAvNorge,
    SisteFlyttingVarInnTilNorge,
    IkkeMuligAaIdentifisereSisteFlytting,
    IngenFlytteInformasjon,
    ErEuEoesStatsborger,
    ErGbrStatsborger,
    ErNorskStatsborger,
    ErFeilretting,
    UgyldigFeilretting,
    #[serde(other)]
    UkjentOpplysning,
}
