INSERT INTO arbeidssoekere (arbeidssoeker_id,
                            identitetsnummer,
                            fornavn,
                            mellomnavn,
                            etternavn,
                            ledig_siden,
                            periode_id,
                            periode_startet,
                            periode_avsluttet,
                            opplysninger_id,
                            opplysninger_tidspunkt,
                            profilering_id,
                            profilert_til,
                            profilering_tidspunkt,
                            egenvurdering_id,
                            egenvurdert_til,
                            egenvurdering_tidspunkt,
                            bekreftelse_id,
                            bekreftelse_gjelder_fra,
                            bekreftelse_gjelder_til,
                            bekreftelse_har_jobbet,
                            bekreftelse_vil_fortsette,
                            bekreftelsesloesning,
                            bekreftelse_paa_vegne_av,
                            inserted_timestamp)
VALUES (545,
        '24849098329',
        'SUNN',
        NULL,
        'VESTIBYLE',
        '2026-04-30 08:02:54',
        'db8270e6-ea64-469f-93b4-69fb07a472c2',
        '2026-04-30 08:02:54',
        NULL,
        '45995166-15f8-4e49-9f3e-0e19fd1a4672',
        '2026-05-21 10:04:29',
        '873241b0-7d0f-4c9c-a442-13fa100870da',
        'OPPGITT_HINDRINGER',
        '2026-05-21 10:04:29',
        NULL,
        NULL,
        NULL,
        '0150ca6d-0bb3-492a-b1fc-6b73d4deba06',
        '2026-05-10 22:00:00',
        '2026-05-24 22:00:00',
        FALSE,
        TRUE,
        'ARBEIDSSOEKERREGISTERET',
        '{}',
        CURRENT_TIMESTAMP);

INSERT INTO arbeidssoekere (arbeidssoeker_id,
                            identitetsnummer,
                            fornavn,
                            mellomnavn,
                            etternavn,
                            ledig_siden,
                            periode_id,
                            periode_startet,
                            periode_avsluttet,
                            opplysninger_id,
                            opplysninger_tidspunkt,
                            profilering_id,
                            profilert_til,
                            profilering_tidspunkt,
                            egenvurdering_id,
                            egenvurdert_til,
                            egenvurdering_tidspunkt,
                            bekreftelse_id,
                            bekreftelse_gjelder_fra,
                            bekreftelse_gjelder_til,
                            bekreftelse_har_jobbet,
                            bekreftelse_vil_fortsette,
                            bekreftelsesloesning,
                            bekreftelse_paa_vegne_av,
                            inserted_timestamp)
VALUES (142894,
        '16488315440',
        'GJENNOMSIKTIG',
        NULL,
        'RØDFOTSULE',
        '2026-06-03 08:17:43',
        'd2151e5d-d3a2-40b1-9a9a-6ae89a85e065',
        '2026-06-03 08:17:43',
        NULL,
        '6ca5db92-b1e5-4171-99b8-50de93aabf7b',
        '2026-06-03 08:17:43',
        '4cf4bcab-65f3-46a2-b7f2-143e7ad5cca4',
        'ANTATT_GODE_MULIGHETER',
        '2026-06-03 08:17:44',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '{}',
        CURRENT_TIMESTAMP);

INSERT INTO arbeidssoekere (arbeidssoeker_id,
                            identitetsnummer,
                            fornavn,
                            mellomnavn,
                            etternavn,
                            ledig_siden,
                            periode_id,
                            periode_startet,
                            periode_avsluttet,
                            opplysninger_id,
                            opplysninger_tidspunkt,
                            profilering_id,
                            profilert_til,
                            profilering_tidspunkt,
                            egenvurdering_id,
                            egenvurdert_til,
                            egenvurdering_tidspunkt,
                            bekreftelse_id,
                            bekreftelse_gjelder_fra,
                            bekreftelse_gjelder_til,
                            bekreftelse_har_jobbet,
                            bekreftelse_vil_fortsette,
                            bekreftelsesloesning,
                            bekreftelse_paa_vegne_av,
                            inserted_timestamp)
VALUES (147226,
        '09448718961',
        'GJENNOMSIKTIG',
        NULL,
        'RØDFOTSULE',
        '2026-06-04 12:59:36',
        'd379a0c3-39e8-4c14-ab3e-2328a3fe80cb',
        '2026-06-04 12:59:36',
        NULL,
        '653c9c38-a5b8-45d5-83b4-4bb3039d03ff',
        '2026-06-04 12:59:36',
        'c95f0d1c-c861-4b93-b0df-2489784e0e0e',
        'ANTATT_BEHOV_FOR_VEILEDNING',
        '2026-06-04 12:59:37',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        '{}',
        CURRENT_TIMESTAMP);