apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-avvist-til-oppgave
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: RUST_BACKTRACE
      value: "1"
    - name: PGSSLMODE
      value: "VerifyFull"
    - name: PGSSLROOTCERT
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_AVVIST_TIL_OPPGAVE_AVVISTTILOPPGAVE_SSLROOTCERT)"
    - name: PGSSLCERT
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_AVVIST_TIL_OPPGAVE_AVVISTTILOPPGAVE_SSLCERT)"
    - name: PGSSLKEY
      value: "$(NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_AVVIST_TIL_OPPGAVE_AVVISTTILOPPGAVE_SSLKEY)"
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 8Mi
    requests:
      memory: 8Mi
      cpu: 1m
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  startup:
    failureThreshold: 10
    initialDelay: 2
    path: /internal/hasStarted
    periodSeconds: 10
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    tracing:
      enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        tier: db-f1-micro
        databases:
          - name: avvisttiloppgave
