name: Kartlegging API - build and deploy
on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - ".github/workflows/kartlegging-api.yml"
      - "app/kartlegging-api/**"
      - "Cargo.toml"
      - "lib/**"
      - "domain/**"
      - "Dockerfile"
env:
  APP_NAME: kartlegging-api
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - run: cargo test -p ${{ env.APP_NAME }}
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ github.workflow_ref }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: docker-build-push
        uses: nais/docker-build-push@2d2b0a7193e65422b7f0355d4afb445e0a8b2cc3 # v0
        id: docker-build-push
        with:
          team: paw
          image_suffix: ${{ env.APP_NAME }}
          build_args: |
            APP=${{ env.APP_NAME }}
            GIT_COMMIT_HASH=${{ github.sha }}
            FEATURES=nais
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
    name: Deploy to dev-gcp
    needs: [test, build]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: app/${{ env.APP_NAME }}/nais/nais-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
