name: Kartlegging API - build and deploy
on:
  push:
    branches:
      - main
      - dev/*
    paths:
      - ".github/workflows/kartlegging-api.yml"
      - "app/kartlegging-api/**"
      - "Cargo.toml"
      - "lib/**"
      - "domain/**"
      - "Dockerfile"
env:
  APP_NAME: kartlegging-api
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          shared-key: "workspace"
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - uses: taiki-e/install-action@1ed6d7be6168f6c9046541087ff549b6bc581fdf # v2.87.2
        with:
          tool: nextest
      - run: cargo nextest run -p ${{ env.APP_NAME }}
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
      - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      - name: docker-build-push
        uses: nais/docker-build-push@2d2b0a7193e65422b7f0355d4afb445e0a8b2cc3 # v0
        id: docker-build-push
        with:
          team: paw
          image_suffix: ${{ env.APP_NAME }}
          build_args: |
            APP=${{ env.APP_NAME }}
            GIT_COMMIT_HASH=${{ github.sha }}
            FEATURES=nais
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/dev')
    name: Deploy to dev-gcp
    needs: [test, build]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: app/${{ env.APP_NAME }}/nais/nais-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to prod-gcp
    needs: [test, build, deploy-dev]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199 # v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: app/${{ env.APP_NAME }}/nais/nais-prod.yaml
          VAR: image=${{ needs.build.outputs.image }}
